__title__ = 'yahoo_weather'
__description__ = 'Python library for yahoo weather new API'
__url__ = 'https://github.com/M-Ahadi/yahoo_weather'
__version__ = '1.0.3'
__author__ = 'Mojtaba Ahadi'
__author_email__ = 'm.ahadi@outlook.com'
__license__ = 'Apache 2.0'